apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ea36e0ogq-python 
  janus-idp.io/tekton: ea36e0ogq-python
  backstage.io/kubernetes-id: ea36e0ogq-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ea36e0ogq-python
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml