apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ea36e0ogq-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ea36e0ogq-python 
  name: ea36e0ogq-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ea36e0ogq-python 
